name: '[dockerimg]'

on:
  push:
    branches: ["master"]

env:
  DOCKER_REGISTRY: 'docker-registry.ebrains.eu/siibra/'
  DOCKER_IMG: 'trafficcop'

  TAG: 'latest'

  EBRAINS_REGISTRY: docker-registry.ebrains.eu
  EBRAINS_NS: docker-registry.ebrains.eu/siibra/trafficcop
  DOCKERHUB_NS: xgui3783/trafficcop
  GH_REGISTRY: ghcr.io
  GH_NS: ${{ github.repository }}

  TMP_TAG: trafficcop


jobs:

  build-docker-img:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - id: build-step
      run: |
        docker build -t ${{ env.TMP_TAG }}:${{ env.TAG }} .
    - run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.GH_REGISTRY }} -u ${{ github.actor }} --password-stdin
        GITHUB_TAG=${{ env.GH_REGISTRY }}/${{ env.GH_NS }}:${{ env.TAG }}
        docker tag ${{ env.TMP_TAG }}:${{ env.TAG }} $GITHUB_TAG
        docker push $GITHUB_TAG
    - run: |
        echo ${{ secrets.DOCKERHUB_SECRET }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
        DOCKERHUB_TAG=${{ env.DOCKERHUB_NS }}:${{ env.TAG }}
        docker tag ${{ env.TMP_TAG }}:${{ env.TAG }} $DOCKERHUB_TAG
        docker push $DOCKERHUB_TAG
    - run: |
        echo '${{ secrets.EBRAINS_DOCKER_REG_TOKEN }}' | docker login ${{ env.EBRAINS_REGISTRY }} -u '${{ secrets.EBRAINS_DOCKER_REG_USER }}' --password-stdin
        EBRAINS_TAG=${{ env.EBRAINS_REGISTRY }}/${{ env.EBRAINS_NS }}:${{ env.TAG }}
        docker tag ${{ env.TMP_TAG }}:${{ env.TAG }} $EBRAINS_TAG
        docker push $EBRAINS_TAG